@startwbs 家庭安全监控系统
* 家庭安全监控系统
** 前端
*** 系统配置页面
**** 配置文件的显示、修改、保存功能
**** 用户头像的上传、删除功能
*** 日志文件页面
**** 读取日志文件夹并支持递归访问功能
**** 在线预览日志文本和图像功能
**** 提供文件的下载功能
*** 视频页面
**** 收取来自后端的帧异步显示视频流功能

** 后端
*** 视频流管理模块
**** 对帧数据进行数据处理
**** 包装帧流为一个数据迭代器

*** 日志，报警模块
**** 日志记录推断的文本信息
**** 保存记录关键帧并录像
**** 邮件实现警报功能并过滤重复报警

*** 推断模型模块
**** 人脸识别模块
***** 载入人脸信息库功能
***** 检测人脸位置，计算人脸编码
***** 未知人脸编码与已知人脸信息库比对生成检测结果

**** 火焰识别模块
***** yolov5模型训练火焰数据库得到权重文件
***** 载入权重和配置文件
***** 对输入帧进行推断给出识别结果


@endwbs

